# Generated by Django 6.0.7 on 2026-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dance_form', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=15)),
            ],
        ),
    ]
